name: Decompress Binaries

on:
  push:
    paths:
      - '**.apk'
      - '**.ipa'
      - '**.exe'
      - '**.deb'
      - '**.zip'
  workflow_dispatch:

jobs:
  decompress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y p7zip-full dpkg-dev

      - name: Find and Decompress Files
        run: |
          mkdir -p extracted_files
          find . -type f \( -name "*.apk" -o -name "*.ipa" -o -name "*.exe" -o -name "*.deb" -o -name "*.zip" \) | while read -r file; do
            echo "Procesando archivo: $file"
            filename=$(basename -- "$file")
            extension="${filename##*.}"
            dirname="extracted_files/${filename}_extracted"
            mkdir -p "$dirname"
            
            case "$extension" in
              apk|ipa|zip)
                unzip -q "$file" -d "$dirname" || echo "Aviso con $filename"
                ;;
              exe)
                7z x "$file" -o"$dirname" -y
                ;;
              deb)
                dpkg-deb -x "$file" "$dirname"
                ;;
            esac
          done

      - name: Upload Extracted Files
        uses: actions/upload-artifact@v4
        with:
          name: decompressed-outputs
          path: extracted_files/
          retention-days: 5
